In [1]:
import torch
import pandas as pd
from torch import nn
from torch import optim
from torch.utils.data import Dataset, DataLoader, random_split

In [2]:
class CustomDataset(Dataset):
    def __init__(self, file_path):
        df = pd.read_csv(file_path)
        self.x1 = df.iloc[:, 0].values
        self.x2 = df.iloc[:, 1].values
        self.x3 = df.iloc[:, 2].values
        self.y = df.iloc[:, 3].values
        self.length = len(df)

    def __getitem__(self, index):
        x = torch.FloatTensor([self.x1[index], self.x2[index], self.x3[index]])
        y = torch.FloatTensor([int(self.y[index])])
        return x, y

    def __len__(self):
        return self.length

In [9]:
class CustomModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = nn.Sequential(
          nn.Linear(3, 1),
          nn.Sigmoid()
        )

    def forward(self, x):
        x = self.layer(x)
        return x

In [4]:
dataset = CustomDataset("/Users/macminim4/PyCharmMiscProject/Aiffel/feb/pytorch/data/datasets/binary.csv")
dataset_size = len(dataset)
train_size = int(dataset_size * 0.8)
validation_size = int(dataset_size * 0.1)
test_size = dataset_size - train_size - validation_size




train_dataset, validation_dataset, test_dataset = random_split(dataset, [train_size, validation_size, test_size], torch.manual_seed(4))
train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True, drop_last=True)
validation_dataloader = DataLoader(validation_dataset, batch_size=4, shuffle=True, drop_last=True)
test_dataloader = DataLoader(test_dataset, batch_size=4, shuffle=True, drop_last=True)

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"
model = CustomModel().to(device)
criterion = nn.BCELoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.0001)

In [6]:
for epoch in range(10000):
    cost = 0.0

    for x, y in train_dataloader:
        x = x.to(device)
        y = y.to(device)

        output = model(x)
        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[-0.3594, -0.2363,  0.5563]], requires_grad=True), Parameter containing:
tensor([0.4447], requires_grad=True)], Cost : 0.714
Epoch : 2000, Model : [Parameter containing:
tensor([[-0.3217, -0.2004,  0.5950]], requires_grad=True), Parameter containing:
tensor([0.4314], requires_grad=True)], Cost : 0.651
Epoch : 3000, Model : [Parameter containing:
tensor([[-0.2970, -0.1746,  0.6208]], requires_grad=True), Parameter containing:
tensor([0.4143], requires_grad=True)], Cost : 0.662
Epoch : 4000, Model : [Parameter containing:
tensor([[-0.2800, -0.1550,  0.6389]], requires_grad=True), Parameter containing:
tensor([0.3948], requires_grad=True)], Cost : 0.631
Epoch : 5000, Model : [Parameter containing:
tensor([[-0.2678, -0.1391,  0.6522]], requires_grad=True), Parameter containing:
tensor([0.3740], requires_grad=True)], Cost : 0.661
Epoch : 6000, Model : [Parameter containing:
tensor([[-0.2588, -0.1258,  0.6623]], requires_grad=True), Parame

In [7]:
with torch.no_grad():
    model.eval()
    for x, y in validation_dataloader:
        x = x.to(device)
        y = y.to(device)
        
        outputs = model(x)

        print(outputs)
        print(outputs >= torch.FloatTensor([0.5]).to(device))
        print("--------------------")

tensor([[0.8500],
        [0.6789],
        [0.6233],
        [0.6530]])
tensor([[True],
        [True],
        [True],
        [True]])
--------------------
tensor([[0.8203],
        [0.8698],
        [0.8618],
        [0.6455]])
tensor([[True],
        [True],
        [True],
        [True]])
--------------------
